name: CI
on:
  push:
    branches:
      - develop
      - 'feat/**'
      - 'fix/**'
      - 'refactor/**'
  pull_request:
    branches:
      - develop
      - main
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  django-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # 개발 도구 있으면: pip install -r requirements-dev.txt

      - name: Django system check
        env:
          SECRET_KEY: dummy
          DEBUG: 'True'
        run: python manage.py check

      - name: Migrations should be up-to-date
        env:
          SECRET_KEY: dummy
          DEBUG: 'True'
        run: python manage.py makemigrations --check --dry-run

      # 선택: 테스트가 있다면 주석 해제
      # - name: Run tests
      #   env:
      #     SECRET_KEY: dummy
      #     DEBUG: 'True'
      #   run: pytest -q