name: Deploy (Render)
on:
  push:
    branches: [main]
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production        # GitHub Environments에서 승인 필요 설정 가능
    steps:
      - uses: actions/checkout@v4

      # 안전용 스모크(아주 얕게)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install deps (smoke)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django check
        env:
          SECRET_KEY: dummy
          DEBUG: 'True'
        run: python manage.py check

      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "Missing RENDER_DEPLOY_HOOK secret"; exit 1
          fi
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK"