# Generated by Django 5.2.6 on 2025-09-11 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(choices=[('TAKEOUT', '포장'), ('BOOTH', '부스')], max_length=20)),
                ('last_no', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number']},
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='orders_order_table_required_for_dinein',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orders_orderitem_qty_gt_0',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='orders_menu_is_acti_9de2c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='orders_menu_categor_10d346_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_t_341304_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_5d7cf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_5dc17d_idx',
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', '매장'), ('TAKEOUT', '포장'), ('BOOTH', '부스')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('SERVE', '서빙화면'), ('COUNTER', '카운터화면'), ('BOOTH', '부스화면')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARING', '준비중'), ('READY', '준비완료'), ('PACKED', '포장완료')], default='PREPARING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('category', 'name')},
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_type', 'DINE_IN'), ('table__isnull', False)), models.Q(('order_type__in', ['TAKEOUT', 'BOOTH']), ('table__isnull', True)), _connector='OR'), name='orders_table_null_check'),
        ),
        migrations.AddIndex(
            model_name='pickupcounter',
            index=models.Index(fields=['date', 'channel'], name='orders_pick_date_935478_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickupcounter',
            unique_together={('date', 'channel')},
        ),
    ]
