# Generated by Django 5.2.6 on 2025-09-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_is_pickup_call_and_clean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='orders_table_null_check',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('SERVE', '홀서빙'), ('COUNTER', '카운터'), ('BOOTH', '야외부스')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_type', 'DINE_IN'), ('table__isnull', False)), models.Q(models.Q(('order_type', 'DINE_IN'), _negated=True), ('table__isnull', True)), _connector='OR'), name='orders_table_null_check'),
        ),
    ]
