# Generated by Django 5.2.6 on 2025-09-12 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_table_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='channel',
            field=models.CharField(choices=[('KITCHEN', '주방'), ('BOOTH', '부스')], default='KITCHEN', max_length=16),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
