# Generated by Django 5.2.6 on 2025-09-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_menuitem_visibility_flags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number']},
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='orders_table_null_check',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='line_total',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='channel',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('BOOTH', 'Booth')], default='KITCHEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine-in'), ('TAKEOUT', 'Takeout'), ('BOOTH', 'Booth')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('SERVE', 'Serve'), ('COUNTER', 'Counter'), ('BOOTH', 'Booth')], default='COUNTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('READY', 'Ready'), ('PACKED', 'Packed')], default='PREPARING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', '-created_at'], name='orders_orde_order_t_577592_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('pickup_no__isnull', False)), fields=('order_type', 'pickup_date', 'pickup_no'), name='uq_type_date_no'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('order_type', 'DINE_IN'), ('table__isnull', False)), models.Q(models.Q(('order_type', 'DINE_IN'), _negated=True), ('table__isnull', True)), _connector='OR')), name='orders_table_null_check'),
        ),
    ]
