# Generated by Django 5.2.6 on 2025-09-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_menuitem_options_alter_table_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickupCounter',
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['sort_index', 'sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__sort_index', 'category__sort_order', 'sort_index', 'name']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['sort_index', 'number', 'id'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='channel',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='sort_index',
            field=models.IntegerField(default=0, help_text='정렬 우선순위(낮을수록 먼저).'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(help_text='가격(원).'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine-in'), ('TAKEOUT', 'Takeout'), ('BOOTH', 'Booth')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('SERVE', 'Serve'), ('COUNTER', 'Counter'), ('BOOTH', 'Booth')], default='COUNTER', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('READY', 'Ready'), ('PACKED', 'Packed')], default='PREPARING', max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, help_text='활성 테이블 여부.'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, default='', help_text='테이블 별칭(선택).', max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(help_text='테이블 번호(유니크).', unique=True),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['sort_index', 'sort_order', 'name'], name='orders_menu_sort_in_35c38c_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_active', 'sort_index', 'name'], name='orders_menu_is_acti_25e629_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_active', 'visible_counter', 'visible_booth', 'visible_kitchen'], name='orders_menu_categor_8bb576_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'menu_item'], name='orders_orde_order_i_5d7cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'id'], name='orders_orde_order_i_5dc17d_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['is_active', 'sort_index', 'number'], name='orders_tabl_is_acti_40e0e7_idx'),
        ),
    ]
