# Generated by Django 5.2.6 on 2025-09-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delete_pickupcounter_alter_menucategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('channel', models.CharField(choices=[('TAKEOUT', 'TAKEOUT'), ('BOOTH', 'BOOTH')], max_length=20)),
                ('last_no', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_t_577592_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_079368_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'created_at'], name='orders_orde_order_t_341304_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='pickupcounter',
            index=models.Index(fields=['date', 'channel'], name='orders_pick_date_935478_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickupcounter',
            unique_together={('date', 'channel')},
        ),
    ]
