# Generated by Django 5.2.6 on 2025-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_pickupcounter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorOrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('floor', models.CharField(choices=[('B1', '지하'), ('F1', '1층')], db_index=True, max_length=2)),
                ('last_no', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PickupCounter',
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['sort_index', 'name']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__sort_index', 'sort_index', 'name']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['sort_index', 'number', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='uq_type_date_no',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='orders_table_null_check',
        ),
        migrations.RemoveIndex(
            model_name='menucategory',
            name='orders_menu_sort_in_35c38c_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_t_341304_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_25e057_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pickup_date',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_pickup_call',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='source',
        ),
        migrations.AddField(
            model_name='order',
            name='order_floor',
            field=models.CharField(blank=True, choices=[('B1', '지하'), ('F1', '1층')], db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', '현금'), ('TICKET', '티켓')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='table_label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', '매장'), ('TAKEOUT', '포장'), ('BOOTH', '부스')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARING', '준비중'), ('READY', '준비완료')], default='PREPARING', max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(help_text='테이블 번호(유니크)', unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['sort_index', 'name'], name='orders_menu_sort_in_2b3432_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('order_no__isnull', False)), fields=('order_floor', 'order_date', 'order_no'), name='uq_floor_date_no'),
        ),
        migrations.AddIndex(
            model_name='floorordercounter',
            index=models.Index(fields=['date', 'floor'], name='orders_floo_date_7aed4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='floorordercounter',
            unique_together={('date', 'floor')},
        ),
    ]
