# Generated by Django 5.2.6 on 2025-09-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_floorordercounter_delete_pickupcounter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorordercounter',
            options={'ordering': ['-date', 'floor']},
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='uq_floor_date_no',
        ),
        migrations.RemoveIndex(
            model_name='menucategory',
            name='orders_menu_sort_in_2b3432_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_floor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table_label',
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(choices=[('B1', '지하'), ('F1', '1층')], default='B1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_takeout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='received_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('ORDER', '서빙(모바일)'), ('B1_COUNTER', '지하 카운터'), ('F1_COUNTER', '1층 카운터'), ('KITCHEN', '주방'), ('F1_BOOTH', '1층 부스')], default='ORDER', max_length=12),
        ),
        migrations.AlterField(
            model_name='floorordercounter',
            name='floor',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', '매장'), ('TAKEOUT', '포장'), ('BOOTH', '부스(1층)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', '현금'), ('TICKET', '티켓')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARING', '준비중'), ('READY', '완료')], default='PREPARING', max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['floor', 'order_type', '-created_at'], name='orders_orde_floor_a30a29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('floor', 'B1'), ('order_type', 'DINE_IN'), ('table__isnull', False)), models.Q(models.Q(('order_type', 'DINE_IN'), _negated=True), ('table__isnull', True)), _connector='OR')), name='orders_table_rule'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('order_no__isnull', False)), fields=('floor', 'order_date', 'order_no'), name='uq_floor_date_no'),
        ),
    ]
