# Generated by Django 5.2.6 on 2025-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_floorordercounter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='floor',
            field=models.CharField(choices=[('B1', '지하'), ('F1', '1층')], default='B1', max_length=2),
        ),
    ]
