# Generated by Django 5.2.6 on 2025-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_payment_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='floor',
            field=models.CharField(choices=[('B1', '지하')], default='B1', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', '매장'), ('TAKEOUT', '포장')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('ORDER', '주문(서빙)'), ('B1_COUNTER', '주방 카운터'), ('KITCHEN', '주방')], default='ORDER', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service_mode',
            field=models.CharField(choices=[('DINE_IN', '매장'), ('TAKEOUT', '포장')], default='DINE_IN', max_length=10),
        ),
    ]
