# Generated by Django 5.2.6 on 2025-10-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_floor_alter_order_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='orders_table_rule',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('floor', 'B1'), ('order_type', 'DINE_IN'), ('table__isnull', False)), models.Q(('floor', 'B1'), ('order_type', 'TAKEOUT'), ('table__isnull', False)), _connector='OR')), name='orders_table_rule'),
        ),
    ]
