# Generated by Django 5.2.17 on 2026-09-15 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_create_floor_sequences"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=32)),
                ("account_id", models.CharField(max_length=150)),
                ("credential_fingerprint", models.CharField(max_length=64)),
                ("refresh_jti_hash", models.CharField(max_length=64)),
                ("previous_jti_hash", models.CharField(blank=True, max_length=64)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("window_started_at", models.DateTimeField()),
                ("failures", models.PositiveIntegerField(default=0)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
