# Generated by Django 5.2.17 on 2026-09-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0023_orderrequest"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("order_type", "TAKEOUT"), ("status__in", ["PREPARING", "READY"])
                ),
                fields=("table",),
                name="uq_active_takeout_slot",
            ),
        ),
    ]
