"""10C: which lineage of the counter a version belongs to (D-019).

Additive and safe on a database that already has orders and a marker in it.
The existing row gets a fresh generation, so every version handed out from now
on carries one; nothing that exists is read or rewritten.

Screens holding a bare number from before this migration are not a problem:
the version format changed with it, so their stored value cannot match a new
one and they fetch once. Rolling back drops the column, and the versions the
older application hands out have no generation in them -- again a mismatch,
again one fetch. Neither direction can leave a screen believing it is current
when it is not, which is the property this column exists for.
"""

# Generated by Django 5.2.17 on 2026-09-20 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_change_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerevision",
            name="generation",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
