"""Takeout is a voucher, not a numbered tag (D-069).

The customer pays, takes a voucher and exchanges it for the food at the
counter. Nobody is looked for by number, so a takeout order holds no table
and no tag: the one-customer-per-tag rule from D-050 (0024) goes, and the
table rule keeps its requirement for dine-in orders only.

Reversal restores both constraints; it fails, by design, while takeout
orders without a table exist -- those rows are the new contract's data.
Generated by Django 5.2.17 on 2026-09-23; docstring added by hand.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_order_departed_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="orders_table_rule",
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="uq_active_takeout_slot",
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("floor", "B1"),
                            ("order_type", "DINE_IN"),
                            ("table__isnull", False),
                        ),
                        models.Q(("floor", "B1"), ("order_type", "TAKEOUT")),
                        _connector="OR",
                    )
                ),
                name="orders_table_rule",
            ),
        ),
    ]
