"""D-073: custom ("기타") order lines entered on the serving screen.

Additive: two new columns with defaults and a nullable menu reference, so
every existing row is already a valid menu line under the new constraint.

Reversing refuses while any custom line exists, matched or not: dropping the
columns would leave those lines with no price, and the old code would count
them as 0 and recompute totals below what was collected. After the first
custom line the only way is forward (PR review M1).
Generated by Django 5.2.17 on 2026-10-03; docstring added by hand.
"""

import django.db.models.deletion
from django.db import migrations, models


def refuse_reverse_over_custom_lines(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    if OrderItem.objects.using(schema_editor.connection.alias).filter(line_amount__isnull=False).exists():
        raise RuntimeError(
            "0032 cannot be reversed: custom order lines exist and would lose their amounts. "
            "Fix forward instead (D-073)."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_takeout_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="custom_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="기타 품목명"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="line_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="기타 줄 합계"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="orders.menuitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("custom_name", ""),
                        ("line_amount__isnull", True),
                        ("menu_item__isnull", False),
                    ),
                    models.Q(
                        ("line_amount__isnull", False),
                        models.Q(("custom_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="orderitem_menu_or_custom",
                violation_error_message="품목은 메뉴 품목이거나, 이름과 금액이 있는 기타 품목이어야 합니다.",
            ),
        ),
        # Last, so that on reverse it runs first, before any schema change.
        migrations.RunPython(migrations.RunPython.noop, refuse_reverse_over_custom_lines),
    ]
