# Generated by Django 5.2.17 on 2026-10-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_orderitem_custom_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CREATED", "주문 생성"),
                    ("STATUS", "상태 변경"),
                    ("PROGRESS", "조리 진행"),
                    ("ITEMS", "품목 수정"),
                    ("DEPARTED", "식당 서빙 출발"),
                ],
                max_length=10,
            ),
        ),
    ]
