"""D-075: persistent receipts for takeout batch completions.

Additive: one new table, no change to existing rows. Reversing refuses while
any receipt exists: dropping them would let a retried completion apply twice.
After the first receipt the only way is forward (same rule as 0032).
Generated by Django 5.2.17 on 2026-10-03; docstring and guard added by hand.
"""

from django.db import migrations, models


def refuse_reverse_over_receipts(apps, schema_editor):
    Receipt = apps.get_model("orders", "TakeoutCompletionRequest")
    if Receipt.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            "0034 cannot be reversed: takeout completion receipts exist and a retried "
            "completion could apply twice without them. Fix forward instead (D-075)."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_mixed_departure_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="TakeoutCompletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("actor", models.CharField(max_length=64)),
                ("fingerprint", models.CharField(max_length=64)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # Last, so that on reverse it runs first, before the table is dropped.
        migrations.RunPython(migrations.RunPython.noop, refuse_reverse_over_receipts),
    ]
